article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    path('file-delete/<int:id>/', views.file_delete, name='file_delete'),
]

paperpower/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path, include
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    {#    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">#}
</head>

<body>
{% include 'header.html' %}
{% block content %}{% endblock content %}
{% include 'footer.html' %}

<script src="{% static 'jquery/jquery-3.6.0.min.js' %}"></script>
<script src="https://cdn.bootcdn.net/ajax/libs/layer/3.5.1/layer.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

templates/footer.html
{% load static %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.dusaiphoto.com 2018</p>
    </div>
</footer>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="#">文献管理系统</a>

        <!-- 导航入口 -->
        <div>
            <ul class="navbar-nav">
                <!-- 条目 -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_create' %}">添加文献信息</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">文献列表</a>
                </li>
                <!-- Django的 if 模板语句 -->
                {% if user.is_authenticated %}
                    <!-- 如果用户已经登录，则显示用户名下拉框 -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a>
                            <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                            <a class="dropdown-item" href='{% url "userprofile:logout" %}'>退出登录</a>
                        </div>
                    </li>
                    <!-- 如果用户未登录，则显示 “登录” -->
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                    </li>
                    <!-- if 语句在这里结束 -->
                {% endif %}
            </ul>
        </div>

        {% if user.is_authenticated %}
            <form
                    style="display:none;"
                    id="user_delete"
                    action="{% url 'userprofile:delete' user.id %}"
                    method="POST"
            >
                {% csrf_token %}
                <button type="submit">发送</button>
            </form>
            <script>
                function user_delete() {
                    // 调用layer弹窗组件
                    layer.open({
                        title: "确认删除",
                        content: "确认删除用户资料吗？",
                        yes: function (index, layero) {
                            $('form#user_delete button').click();
                            layer.close(index);
                        },
                    })
                }
            </script>
        {% endif %}

    </div>
</nav>