article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    path('file-delete/<int:id>/', views.file_delete, name='file_delete'),
]

paperpower/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.utils import timezone
from taggit.managers import TaggableManager


class PaperInfo(models.Model):
    title = models.CharField(max_length=100)  # 文章标题
    author = models.CharField(max_length=100, blank=True)
    paper_author = models.CharField(max_length=100)  # 文章的作者/团队
    source = models.CharField(max_length=100)  # 文章的来源：期刊or会议
    reference = models.CharField(max_length=500, blank=True)  # 参考文献
    pdf_file = models.FileField(upload_to="pdfFiles/", blank=True)  # pdf
    tags = TaggableManager(blank=True)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

article/forms.py
from django import forms
from .models import PaperInfo


class PaperInfoForm(forms.ModelForm):
    class Meta:
        model = PaperInfo
        fields = (
            'title',
            'author',
            'paper_author',
            'source',
            'body',
            'tags',
            'reference',
            'pdf_file'
        )

article/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import PaperInfo
import markdown
from .forms import PaperInfoForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
import os
from paperpower import settings


# 视图函数
def article_list(request):
    search = request.GET.get('search')
    tag = request.GET.get('tag')

    articles_list = PaperInfo.objects.all()

    if search:
        articles_list = articles_list.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        search = ''

    # 标签查询集
    if tag and tag != 'None':
        articles_list = articles_list.filter(tags__name__in=[tag])

    paginator = Paginator(articles_list, 5)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    context = {
        'articles': articles,
        'search': search,
        'tag': tag,
    }
    return render(request, 'article/list.html', context)


def article_detail(request, id):
    # 取出相应的文章
    article = PaperInfo.objects.get(id=id)
    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ]
    )
    article.body = md.convert(article.body)
    # 需要传递给模板的对象
    context = {'article': article, 'toc': md.toc}
    # 载入模板，并返回context对象
    return render(request, 'article/detail.html', context)


@login_required(login_url='/userprofile/login/')
def article_create(request):
    if request.method == "POST":
        article_post_form = PaperInfoForm(data=request.POST, files=request.FILES)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)
            new_article.save()
            article_post_form.save_m2m()
            return redirect("article:article_list")
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    else:
        article_post_form = PaperInfoForm()
        context = {'article_post_form': article_post_form}
        return render(request, 'article/create.html', context)


# 安全删除文章
@login_required(login_url='/userprofile/login/')
def article_safe_delete(request, id):
    if request.method == 'POST':
        article = PaperInfo.objects.get(id=id)
        if request.user.username != article.author:
            return HttpResponse("抱歉，你无权删除这篇文章。")
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("仅允许post请求")


# 更新文章
@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    article = PaperInfo.objects.get(id=id)
    if request.user.username != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")

    if request.method == "POST":
        article_post_form = PaperInfoForm(data=request.POST, files=request.FILES)
        if article_post_form.is_valid():
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.paper_author = request.POST['paper_author']
            article.source = request.POST['source']
            article.reference = request.POST['reference']
            if 'pdf_file' in request.FILES:
                if article.pdf_file.name != '':
                    file_name = article.pdf_file.name
                    d = settings.MEDIA_ROOT
                    file_path = os.path.join(d, file_name)
                    if os.path.exists(file_path):
                        os.remove(file_path)
                    article.pdf_file.delete()
                article.pdf_file = request.FILES['pdf_file']
            article.tags.set(request.POST.get('tags').split(','), clear=True)
            article.save()
            return redirect("article:article_detail", id=id)
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    else:
        article_post_form = PaperInfoForm()
        context = {
            'article': article,
            'article_post_form': article_post_form,
            'tags': ','.join([x for x in article.tags.names()]),
        }
        # 将响应返回到模板中
        return render(request, 'article/update.html', context)


from django.conf import settings


@login_required(login_url='/userprofile/login/')
def file_delete(request, id):
    article = PaperInfo.objects.get(id=id)
    file_path = article.pdf_file.name
    d = settings.MEDIA_ROOT
    os.remove(os.path.join(d, file_path))
    article.pdf_file.delete()
    article.save()
    return redirect("article:article_update", id=id)

templates/article/detail.html
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

    <!-- 文章详情 -->
    <div class="container">
        <div class="row">
            <div class="col-9">
                <!-- 标题及作者 -->
                <h1 class="mt-4 mb-4">{{ article.title }}</h1>
                <div class="alert alert-success">
                    作者：{{ article.author }}
                    {% if user.username == article.author %}
                        · <a href="#" onclick="confirm_safe_delete()">删除文章</a>
                        · <a href="{% url "article:article_update" article.id %}">编辑文章</a>
                    {% endif %}
                </div>

                <!-- 文章的基本信息 -->
                <div class="col-12">
                    <p>文献PDF:
                        {% if article.pdf_file != '' %}
                            <a href="{{ article.pdf_file.url }}" class="btn btn-primary" style="cursor: pointer;"
                               id="preview_link">预览</a>
                        {% else %}
                            ~
                        {% endif %}
                    </p>
                    <p>作者/团队: {{ article.paper_author|safe }}</p>
                    <p>文章出处: {{ article.source|safe }}</p>
                    <p>参考文献: {{ article.reference|safe }}</p>
                </div>

                <!-- 文章正文 -->
                <div class="col-12">
                    <p>{{ article.body|safe }}</p>
                </div>
            </div>

            <!-- 新增的目录 -->
            <div class="col-3 mt-4">
                <h4><strong>目录</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>
    </div>

    <form
            style="display:none;"
            id="safe_delete"
            action="{% url 'article:article_safe_delete' article.id %}"
            method="POST"
    >
        {% csrf_token %}
        <button type="submit">发送</button>
    </form>

    <script>
        function confirm_safe_delete() {
            layer.open({
                title: "确认删除",
                content: "确认删除这篇文章吗？",
                yes: function (index, layero) {
                    $('form#safe_delete button').click();
                    layer.close(index);
                }
            })
        }

    </script>

{% endblock content %}

templates/article/list.html
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

    <!-- 定义放置文章标题的div容器 -->
    <br>
    <div class="container">
        <!-- 新增，搜索栏 -->
        <div class="row">
            <div class="col-auto mr-auto">
                <form class="form-inline">
                    <label class="sr-only">content</label>
                    <input type="text"
                           class="form-control mb-2 mr-sm-2"
                           name="search"
                           placeholder="搜索文章..."
                           required
                    >
                </form>
            </div>
        </div>

        <!-- 新增，搜索提示语 -->
        {% if search %}
            {% if articles %}
                <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
                <hr>
            {% else %}
                <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
                <hr>
            {% endif %}
        {% endif %}

        <div class="row mt-2">
            {% for article in articles %}
                <!-- 文章内容 -->
                <div class="col-12">
                    <!-- 标题 -->
                    <h3>
                        <b>
                            <a href="{% url 'article:article_detail' article.id %}"
                               style="color: black;"
                            >
                                {{ article.title }}
                            </a>
                        </b>
                    </h3>
                    <!-- 标签 -->
                    <span>
                        {% for tag in article.tags.all %}
                            <a href="{% url 'article:article_list' %}?tag={{ tag }}"
                               class="badge badge-primary"
                               style="background: green"
                            >
                                {{ tag }}
                            </a>
                        {% endfor %}
                    </span>
                    <!-- 显示基本信息TODO -->
                    <div>
                        <p style="color: gray;">
                            {{ article.body|slice:'100' }}...
                        </p>
                    </div>
                    <hr>
                </div>
            {% endfor %}

        </div>
        <!-- 页码导航 -->
        <div class="pagination row">
            <div class="m-auto">
        <span class="step-links">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if articles.has_previous %}
                <a href="?page=1&search={{ search }}&column={{ column }}&tag={{ tag }}" class="btn btn-success">
                    &laquo; 1
                </a>
                <span>...</span>
                <a href="?page={{ articles.previous_page_number }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                   class="btn btn-secondary"
                >
                    {{ articles.previous_page_number }}
                </a>
            {% endif %}

            <!-- 当前页面 -->
            <span class="current btn btn-danger btn-lg">
                {{ articles.number }}
            </span>

            <!-- 如果不是最末页，则显示下翻按钮 -->
            {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                   class="btn btn-secondary"
                >
                    {{ articles.next_page_number }}
                </a>
                <span>...</span>
                <a href="?page={{ articles.paginator.num_pages }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                   class="btn btn-success"
                >
                    {{ articles.paginator.num_pages }} &raquo;
                </a>
            {% endif %}
        </span>
            </div>
        </div>

    </div>
{% endblock content %}

templates/article/update.html
{% extends "base.html" %} {% load static %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">文章标题</label>
                        <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                        <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                    </div>

                    <!-- 作者团队 -->
                    <div class="form-group">
                        <!-- 标签 -->
                        <label for="paper_author">作者/团队</label>
                        <!-- 文本框 -->
                        <input type="text" class="form-control form-control col-8" id="paper_author" name="paper_author"
                               value="{{ article.paper_author }}">
                    </div>

                    <!-- 文章出处 -->
                    <div class="form-group">
                        <!-- 标签 -->
                        <label for="source">文章出处</label>
                        <!-- 文本框 -->
                        <input type="text" class="form-control form-control col-8" id="source" name="source"
                               value="{{ article.source }}">
                    </div>


                    <!-- 参考文献 -->
                    <div class="form-group">
                        <!-- 标签 -->
                        <label for="reference">参考文献</label>
                        <!-- 文本框 -->
                        <textarea type="text"
                                  class="form-control form-control col-8"
                                  id="reference"
                                  name="reference"
                                  rows="3"
                        >{{ article.reference }}</textarea>
                    </div>

                    <!-- bitex -->
                    <div>
                        <label for="bitex">Bitex自动转换</label>
                        <button type="button" class="btn btn-primary" size="10" onclick="convertText()">转换</button>
                        <br>
                        <textarea id="inputText"
                                  class="form-control form-control col-8"
                                  name="bitex" rows="5"
                                  cols="50"
                                  placeholder="在这里输入..."
                        ></textarea>
                    </div>


                    <div>
                        <br>
                        <label for="pdf_file">上传pdf</label>
                        <br>
                        <input type="file"
                               class="form-control-file col-2"
                               name="pdf_file"
                               id="pdf_file"
                               accept=".pdf"
                               onchange="handleUpload()"
                               style="padding-left: 0; display: inline-block"
                        >
                        <button type="button" class="btn btn-primary" size="3" id="pdf_link"
                                onclick="handleFilePreview()" style="display: none; cursor: pointer">
                            预览
                        </button>
                        {% if article.pdf_file == '' %}

                        {% else %}
                            <a href="{{ article.pdf_file.url }}" class="btn btn-primary" style="cursor: pointer"
                               id="preview_link">预览</a>
                            <a href="{% url 'article:file_delete' article.id %}"
                               class="btn btn-primary"
                               style="cursor: pointer"
                               id="file_delete"
                               onclick="confirm_file_delete()"
                            >删除</a>
                            <label id="preview_name"> {{ article.pdf_file.name }}</label>
                        {% endif %}
                        <br>
                        <br>
                    </div>


                    <!-- 文章标签-->
                    <div class="form-group">
                        <label for="tags">标签</label>
                        <input type="text" class="form-control col-3" id="tags" name="tags"
                               value="{{ tags }}">
                    </div>

                    <div class="form-group">
                        <label for="body">文章正文</label>
                        <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                        <textarea type="text" class="form-control" id="body" name="body"
                                  rows="12">{{ article.body }}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>

    <script>
        function isMatch(content, target) {
            const match = content.match(target);
            if (match !== null) {
                return match[1];
            }
            return null;
        }

        function parseConference(content) {
            // parse title
            const title = isMatch(content, /title={([^}]+)}/);
            if (title === null) {
                throw new Error("No title found.");
            }

            // parse authors
            let authors = isMatch(content, /author={([^}]+)}/);
            if (authors === null) {
                throw new Error("No authors found.");
            }
            authors = authors.split(' and ');
            let newAuthors = "";
            for (let i = 0; i < authors.length; i++) {
                if (i > 2) {
                    newAuthors += 'et al.';
                    break;
                }
                const author = authors[i].split(' ');
                const formattedAuthor = author[0] + ' ' + author[1][0];
                newAuthors += formattedAuthor;
                if (i === authors.length - 1) {
                    newAuthors += '.';
                } else {
                    newAuthors += ', ';
                }
            }

            // parse booktitle
            const booktitle = isMatch(content, /booktitle={([^}]+)}/);
            if (booktitle === null) {
                throw new Error("No book title.");
            }

            // parse year
            const year = isMatch(content, /year={([^}]+)}/);
            if (year === null) {
                throw new Error("No year found.");
            }

            // parse pages
            const pages = isMatch(content, /pages={([^}]+)}/);

            // / author, "title," in booktitle, year, pp.(pages). /
            const reference = `${newAuthors} "${title}," in ${booktitle}, ${year}${pages ? `, pp. ${pages}` : ""}.`;

            return [reference, title, newAuthors, booktitle + ' ' + year];
        }

        function parseJournal(content) {
            // parse title
            const title = isMatch(content, /title={([^}]+)}/);
            if (title === null) {
                throw new Error("No title found.");
            }

            // parse authors
            let authors = isMatch(content, /author={([^}]+)}/);
            if (authors === null) {
                throw new Error("No authors found.");
            }
            authors = authors.split(' and ');
            let newAuthors = "";
            for (let i = 0; i < authors.length; i++) {
                if (i > 2) {
                    newAuthors += 'et al.';
                    break;
                }
                const author = authors[i].split(' ');
                const formattedAuthor = author[0] + ' ' + author[1][0];
                newAuthors += formattedAuthor;
                if (i === authors.length - 1) {
                    newAuthors += '.';
                } else {
                    newAuthors += ', ';
                }
            }

            // parse journal
            const journal = isMatch(content, /journal={([^}]+)}/);
            if (journal === null) {
                throw new Error("No book title.");
            }

            // parse pages
            const year = isMatch(content, /year={([^}]+)}/);
            if (year === null) {
                throw new Error("No year found.");
            }

            // parse pages
            const pages = isMatch(content, /pages={([^}]+)}/);

            // parse volume
            const volume = isMatch(content, /volume={([^}]+)}/);

            // parse number
            const number = isMatch(content, /number={([^}]+)}/);

            // /author, "title," in journal, vol. (volume), no. (number), pp. (pages), year./
            const reference = `${newAuthors} "${title}," in ${journal}${volume ? `, vol. ${volume}` : ""}${number ? `, no. ${number}` : ""}${pages ? `, pp. ${pages}` : ""}, ${year}.`;

            return [reference, title, newAuthors, journal + ' ' + year];
        }

        function parseBitex(content) {
            const conferenceMatch = content.match(/@inproceedings{/);
            if (conferenceMatch !== null) {
                return parseConference(content);
            }
            const journalMatch = content.match(/@article{/);
            if (journalMatch !== null) {
                return parseJournal(content);
            }

            if (conferenceMatch === null && journalMatch === null) {
                throw new Error("Neither conference nor journal, check bitex content.");
            }
        }


        function convertText() {
            // 获取输入文本
            var inputText = document.getElementById('inputText').value;
            var converted_text = parseBitex(inputText);
            let [ref, title, authors, source] = converted_text
            document.getElementById('reference').value = ref;
            document.getElementById('title').value = title;
            document.getElementById('paper_author').value = authors;
            document.getElementById('source').value = source;
        }

        function handleUpload() {
            const fileInput = document.getElementById('pdf_file');
            const file = fileInput.files[0];
            const pdfLink = document.getElementById('pdf_link');
            const previewLink = document.getElementById('preview_link');
            const previewName = document.getElementById('preview_name');
            const pdfDelete = document.getElementById('file_delete');
            if (file) {
                pdfLink.style.display = 'inline-block';
                previewLink.style.display = 'none';
                previewName.style.display = 'none';
                pdfDelete.style.display = 'none';
            }
        }

        function handleFilePreview() {
            const fileInput = document.getElementById('pdf_file');
            const file = fileInput.files[0];

            if (file) {
                const reader = new FileReader();

                reader.onload = function (e) {
                    const blob = new Blob([new Uint8Array(e.target.result)], {type: 'application/pdf'});
                    const url = URL.createObjectURL(blob);

                    window.open(url, '_blank');

                    URL.revokeObjectURL(url);
                };

                reader.readAsArrayBuffer(file);
            }
        }

        function confirm_file_delete() {
            const r = confirm("确定删除这篇文献PDF吗？");
            if (r) {
                alert("删除成功");
                return true;
            }
            return false;
        }
    </script>
{% endblock content %}